In [1]:

import numpy as np
#1 Dimensional Array:
a = np.array([1,2,3])
print(a)
#2 Dimensional Array:
b = np.array([[1,2,3],[4,5,6]])
print(b)
#3x4 array of zeroes:
c = np.zeros((3,4))
print(c)
#Arrange numbers between lower (1) and upper limit (10) with an interval of 3:
d = np.arange(1,10,3)
print(d)
#Printing even numbers between 10 and 20:
x = np.arange(10,20,2)
print(x)
#Arrange 'x' numbers with equal spacing between lower (1) and upper (20) limit:
y = np.linspace(1,20,4)
print(y)
#Have an array of the same value:
z = np.full((2,3),6)
print(z)
#Fill array of any size with random values:
o = np.random.random((10, 12))
print(o)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1 4 7]
[10 12 14 16 18]
[ 1.          7.33333333 13.66666667 20.        ]
[[6 6 6]
 [6 6 6]]
[[0.19070603 0.43707842 0.28355015 0.05019296 0.26113556 0.682333
  0.81336311 0.83318662 0.28105374 0.24691074 0.60066179 0.16102948]
 [0.41210892 0.1352005  0.68687004 0.16088727 0.9946058  0.99344148
  0.25480357 0.45584719 0.25896187 0.38974506 0.91011905 0.9832167 ]
 [0.56885179 0.4480689  0.10835649 0.99279679 0.60450938 0.62789021
  0.23576765 0.25030059 0.41181041 0.81712353 0.43275361 0.74809564]
 [0.59050375 0.90039894 0.50053829 0.37989428 0.83750175 0.90210756
  0.61974617 0.6271147  0.32847733 0.56073374 0.6634392  0.27958599]
 [0.27181287 0.58387691 0.88344059 0.53507877 0.28036598 0.60983003
  0.64870717 0.32112928 0.44662937 0.88185186 0.55846321 0.63173044]
 [0.99144313 0.26737765 0.98138226 0.68221156 0.07910652 0.8774451
  0.12139387 0.04752029 0.41546758 0.57262966 0.71854127 0.18088717]
 [0.24338466 0

In [2]:
a = np.arange(24)
a
print (a.ndim)
#reshaping this array
b = a.reshape(2,4,3)
b

1


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [3]:
a = np.arange(25)
print(a.size)

25


In [4]:
d= np.array([[1,2,3,4,5],[0,1,4,5,6],[7,8,9,101,11]])
print(d.size)
print(d.dtype)

15
int32


In [5]:
e = np.arange(24, dtype=float)
print(e, e.dtype)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.] float64


In [6]:
np.sum([10,20])

30

In [7]:
v, b=50,70
np.sum([v,b])

120

In [8]:
np.sum([[1,2],[5,6]], axis=0)

array([6, 8])

In [9]:
np.sum([[1,2,3],[4,5,6],[6,7,8]], axis = 0)

array([11, 14, 17])

In [10]:
#Array comparision
a = [10,2,3]
b= [6,7,8]
c = [10,2,3]
np.array_equal(a,c)

True

In [11]:
print("Sum: ", np.sum(a))
print("Mean: ", np.mean(a))
print("Median: ", np.median(a))
print("Standard Deviation: ", np.std(a))

Sum:  15
Mean:  5.0
Median:  3.0
Standard Deviation:  3.559026084010437


In [12]:
np.hstack((a,b))

array([10,  2,  3,  6,  7,  8])

In [13]:
np.vstack((a,b))

array([[10,  2,  3],
       [ 6,  7,  8]])

In [14]:
np.row_stack((a,b))

array([[10,  2,  3],
       [ 6,  7,  8]])

In [15]:
np.column_stack((a,b))

array([[10,  6],
       [ 2,  7],
       [ 3,  8]])

In [16]:
z= np.arange(16).reshape(8,2)
print(np.vsplit(z,2))

[array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]]), array([[ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])]


In [17]:
a = ['m','o','n','t','y',' ','p', 'y','t','h','o','n']
a[2:9]

['n', 't', 'y', ' ', 'p', 'y', 't']

In [25]:
ar1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
#Printing the first two elements of the first row
ar1[:1, :2]


array([[1, 2]])

In [26]:
#Printing the last two elements of the first row
ar1[:1, 1:]

array([[2, 3]])

In [10]:
import numpy as np
import sys

#Defining a list
l = range(1000)
print("Size of a list: ", sys.getsizeof(1)*len(l))

#Defining a numpy array
a = np.arange(1000)
print("Size of a numpy array: ", a.size*a.itemsize)

Size of a list:  28000
Size of a numpy array:  4000


In [15]:
#Speed comparision, numpy vs list
import time
def using_list():
    t1 = time.time()   #Starting/Initial time
    X = range (10000)
    Y = range (10000)
    z = [X[i]+Y[i] for i in range (len(X))]
    return time.time() - t1  #time.time() means return time after the statements above have been processed minus initial time
    
def using_numpy():
    t1 = time.time()
    a = np.arange(10000)
    b = np.arange(10000)
    z = a+b 
    return time.time() - t1

#Calling these functions:
list_time = using_list()
numpy_time = using_numpy()
print ("Time taken by lists:", list_time)
print("Time taken by numpy: ", numpy_time)
print("Therefore using numpy is " +str(list_time/numpy_time)+ "times faster than using a list")


Time taken by lists: 0.0019941329956054688
Time taken by numpy:  0.000997304916381836
Therefore using numpy is 1.9995218742529286times faster than using a list
