In [1]:

import numpy as np

In [2]:
a = np.arange(24)
a
print (a.ndim)
#reshaping this array
b = a.reshape(2,4,3)
b

1


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [3]:
a = np.arange(25)
print(a.size)

25


In [4]:
d= np.array([[1,2,3,4,5],[0,1,4,5,6],[7,8,9,101,11]])
print(d.size)
print(d.dtype)

15
int32


In [5]:
e = np.arange(24, dtype=float)
print(e, e.dtype)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.] float64


In [6]:
np.sum([10,20])

30

In [7]:
v, b=50,70
np.sum([v,b])

120

In [8]:
np.sum([[1,2],[5,6]], axis=0)

array([6, 8])

In [9]:
np.sum([[1,2,3],[4,5,6],[6,7,8]], axis = 0)

array([11, 14, 17])

In [10]:
#Array comparision
a = [10,2,3]
b= [6,7,8]
c = [10,2,3]
np.array_equal(a,c)

True

In [11]:
print("Sum: ", np.sum(a))
print("Mean: ", np.mean(a))
print("Median: ", np.median(a))
print("Standard Deviation: ", np.std(a))

Sum:  15
Mean:  5.0
Median:  3.0
Standard Deviation:  3.559026084010437


In [12]:
np.hstack((a,b))

array([10,  2,  3,  6,  7,  8])

In [13]:
np.vstack((a,b))

array([[10,  2,  3],
       [ 6,  7,  8]])

In [14]:
np.row_stack((a,b))

array([[10,  2,  3],
       [ 6,  7,  8]])

In [15]:
np.column_stack((a,b))

array([[10,  6],
       [ 2,  7],
       [ 3,  8]])

In [16]:
z= np.arange(16).reshape(8,2)
print(np.vsplit(z,2))

[array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]]), array([[ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])]


In [17]:
a = ['m','o','n','t','y',' ','p', 'y','t','h','o','n']
a[2:9]

['n', 't', 'y', ' ', 'p', 'y', 't']

In [25]:
ar1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
#Printing the first two elements of the first row
ar1[:1, :2]


array([[1, 2]])

In [26]:
#Printing the last two elements of the first row
ar1[:1, 1:]

array([[2, 3]])

In [10]:
import numpy as np
import sys

#Defining a list
l = range(1000)
print("Size of a list: ", sys.getsizeof(1)*len(l))

#Defining a numpy array
a = np.arange(1000)
print("Size of a numpy array: ", a.size*a.itemsize)

Size of a list:  28000
Size of a numpy array:  4000


In [15]:
#Speed comparision, numpy vs list
import time
def using_list():
    t1 = time.time()   #Starting/Initial time
    X = range (10000)
    Y = range (10000)
    z = [X[i]+Y[i] for i in range (len(X))]
    return time.time() - t1  #time.time() means return time after the statements above have been processed minus initial time
    
def using_numpy():
    t1 = time.time()
    a = np.arange(10000)
    b = np.arange(10000)
    z = a+b 
    return time.time() - t1

#Calling these functions:
list_time = using_list()
numpy_time = using_numpy()
print ("Time taken by lists:", list_time)
print("Time taken by numpy: ", numpy_time)
print("Therefore using numpy is " +str(list_time/numpy_time)+ "times faster than using a list")


Time taken by lists: 0.0019941329956054688
Time taken by numpy:  0.000997304916381836
Therefore using numpy is 1.9995218742529286times faster than using a list
